# Generated by Django 2.0.3 on 2018-04-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganme', models.CharField(max_length=20)),
                ('gstudentnum', models.IntegerField()),
                ('ggirlnum', models.IntegerField()),
                ('gboynum', models.IntegerField()),
            ],
        ),
    ]
